# Generated by Django 2.0.6 on 2019-05-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DCategory',
            fields=[
                ('category', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=40, null=True)),
                ('book_counts', models.IntegerField(blank=True, null=True)),
                ('category_pid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'd_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DOrderiterm',
            fields=[
                ('shop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('shop_num', models.IntegerField(blank=True, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'd_orderiterm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TAddress',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('detail_address', models.CharField(blank=True, max_length=200, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('telphone', models.IntegerField(blank=True, null=True)),
                ('addr_mobile', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TBook',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(blank=True, max_length=100, null=True)),
                ('market_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dang_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sales_volume', models.IntegerField(blank=True, null=True)),
                ('upload_date', models.CharField(blank=True, max_length=40, null=True)),
                ('author', models.CharField(blank=True, max_length=40, null=True)),
                ('press', models.CharField(blank=True, max_length=40, null=True)),
                ('publish_date', models.CharField(blank=True, max_length=40, null=True)),
                ('edition', models.IntegerField(blank=True, null=True)),
                ('print_time', models.CharField(blank=True, max_length=40, null=True)),
                ('num_print', models.CharField(blank=True, max_length=40, null=True)),
                ('isbn', models.CharField(blank=True, db_column='ISBN', max_length=40, null=True)),
                ('w_num', models.CharField(blank=True, max_length=40, null=True)),
                ('p_num', models.CharField(blank=True, max_length=40, null=True)),
                ('format', models.CharField(blank=True, max_length=40, null=True)),
                ('paper_type', models.CharField(blank=True, max_length=40, null=True)),
                ('pack_type', models.CharField(blank=True, max_length=40, null=True)),
                ('editor_choice', models.TextField(blank=True, null=True)),
                ('content_abstract', models.TextField(blank=True, null=True)),
                ('author_blurb', models.TextField(blank=True, null=True)),
                ('t_index', models.TextField(blank=True, null=True)),
                ('t_media', models.TextField(blank=True, null=True)),
                ('t_illustration', models.TextField(blank=True, null=True)),
                ('pic_path', models.TextField(blank=True, null=True)),
                ('series_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_socre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('book_status', models.IntegerField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TOrder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('num', models.CharField(blank=True, max_length=20, null=True)),
                ('create_time', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(blank=True, max_length=20, null=True)),
                ('t_email', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_user',
                'managed': False,
            },
        ),
    ]
