# Generated by Django 2.0.6 on 2019-05-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dangdangapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOrder_ok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_code', models.CharField(max_length=200)),
                ('t_userid', models.IntegerField()),
            ],
            options={
                'db_table': 't_orderok',
            },
        ),
    ]
