# Generated by Django 2.0.6 on 2019-05-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dangdangapp', '0004_auto_20190525_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torder_ok',
            name='t_userid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
